name: Validate Images (CI)

on:
  pull_request:
    paths:
      - 'images/**'
  push:
    branches:
      - main
    paths:
      - 'images/**'

env:
  REGISTRY: ghcr.io

jobs:
  validate:
    name: Validate Dockerfiles
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        image: [k8s-backup-tools, k8s-config-tools]
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4

      - name: Build image (Validate Only)
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7
        with:
          context: ./images/${{ matrix.image }}
          push: false
          load: true
          tags: ${{ env.REGISTRY }}/hononeko/${{ matrix.image }}:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
