name: Validate Images (CI)

on:
  pull_request:
    paths:
      - 'images/**'
  push:
    branches:
      - main
    paths:
      - 'images/**'

env:
  REGISTRY: ghcr.io

jobs:
  validate:
    name: Validate Dockerfiles
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        image: [k8s-backup-tools, k8s-config-tools]
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4

      - name: Build image (Validate Only)
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7
        with:
          context: ./images/${{ matrix.image }}
          push: false
          load: true
          tags: ${{ env.REGISTRY }}/hononeko/${{ matrix.image }}:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
